---
root: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
  project: './tsconfig.json'
env:
  es2022: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
plugins:
  - 'import'
  - '@typescript-eslint'
rules:
  valid-jsdoc: 'error'
  import/no-extraneous-dependencies:
    - 'error'
    - peerDependencies: true
      devDependencies: true
  class-methods-use-this: 0
  import/extensions:
    - 'error'
    - 'always'
    - ignorePackages: true
  prefer-const: 0
  '@typescript-eslint/no-unused-vars': ['warn', { ignoreRestSiblings: true }]
overrides:
  - files:
      - 'packages/**/src/**/*@(.mjs|.js|.ts|.cjs|.jsx|.tsx)'
    rules:
      import/no-extraneous-dependencies:
        - 'error'
        - peerDependencies: true
          devDependencies: false
      no-console: 'error'
  - files:
      - '*.cjs'
    parserOptions:
      sourceType: 'script'
    env:
      node: true
  - files:
      - 'packages/**/bin/**/*@(.mjs|.js|.ts|.cjs)'
    env:
      node: true
