---
root: true
parserOptions:
  sourceType: 'module'
env:
  es2022: true
extends:
  - 'eslint:recommended'
  - 'prettier'
plugins:
  - 'import'
rules:
  valid-jsdoc: 'error'
  import/no-extraneous-dependencies:
    - 'error'
    - peerDependencies: true
  class-methods-use-this: 0
  import/extensions:
    - 'error'
    - 'always'
    - ignorePackages: true
overrides:
  - files:
      - 'packages/**/__tests__/**/*@(.mjs|.js)'
      - 'packages/**/*.test@(.mjs|.js)'
    env:
      jest: true
      node: true
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
          peerDependencies: true
  - files:
      - '*.cjs'
    parserOptions:
      sourceType: 'script'
    env:
      node: true
