packages:
  - packages/*

catalog:
  typescript: 5.8.3
  cross-env: ^7.0.3
  vite: ^6.1.0
  vitest: 3.1.1
  '@vitest/ui': 3.1.1
  tsx: ^4.19.3
  '@types/node': ^22.14.0

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - msw
