packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'

catalog:
  'typescript': '5.3.2'
  'cross-env': '^7.0.3'
  'vite': '^6.0.7'
  # Pin vitest version because testing types is experimental.
  'vitest': '3.0.1'
  'tsx': '^4.7.0'
