packages:
  - packages/*

catalog:
  typescript: npm:@typescript/typescript6@^6.0.2
  '@typescript/native': npm:typescript@^7.0.2
  cross-env: ^7.0.3
  vite: ^6.4.1
  vitest: 4.1.11
  '@vitest/ui': 4.1.11
  '@types/node': ^26.6.3

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - msw
