packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'

catalog:
  'typescript': '5.8.3'
  'cross-env': '^7.0.3'
  'vite': '^6.1.0'
  # Pin vitest version because testing types is experimental.
  'vitest': '3.1.1'
  '@vitest/ui': '3.1.1'
  'tsx': '^4.19.3'
  '@types/node': '^20.17.19'
