/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current session (check login) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            /** @enum {string} */
                            role: "host" | "participant";
                            runs: {
                                experimentName: string;
                                runName: string;
                                /** @enum {string} */
                                runStatus: "idle" | "running" | "completed" | "interrupted" | "canceled";
                            }[];
                        };
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
            };
        };
        /** Set the current session (login) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body */
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @default participant
                         * @enum {string}
                         */
                        role?: "host" | "participant";
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description 201 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            /** @enum {string} */
                            role: "host" | "participant";
                            runs: {
                                experimentName: string;
                                runName: string;
                                /** @enum {string} */
                                runStatus: "idle" | "running" | "completed" | "interrupted" | "canceled";
                            }[];
                        };
                    };
                };
                /** @description 400 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
                /** @description 403 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /** Delete the current session (logout) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 201 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
                /** @description 403 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new run */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body */
            requestBody?: {
                content: {
                    "application/json": {
                        experimentName?: string;
                        runName?: string;
                        /**
                         * @default idle
                         * @enum {string}
                         */
                        runStatus?: "idle" | "running" | "completed" | "interrupted" | "canceled";
                    };
                };
            };
            responses: {
                /** @description 201 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            url: string;
                            experimentName: string;
                            runName: string;
                            runStatus: string;
                        };
                    };
                };
                /** @description 400 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
                /** @description 403 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/{experimentName}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get information about all runs of an experiment */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    experimentName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            runs: {
                                url: string;
                                runCreatedAt: string;
                                runName: string;
                                experimentName: string;
                                /** @enum {string} */
                                runStatus: "idle" | "running" | "completed" | "interrupted" | "canceled";
                                logs: {
                                    type: string;
                                    count: number;
                                    pending: number;
                                    lastNumber: number;
                                }[];
                            }[];
                        };
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/{experimentName}/runs/{runName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get information about a run */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    experimentName: string;
                    runName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            run: {
                                url: string;
                                runCreatedAt: string;
                                runName: string;
                                experimentName: string;
                                /** @enum {string} */
                                runStatus: "idle" | "running" | "completed" | "interrupted" | "canceled";
                                logs: {
                                    type: string;
                                    count: number;
                                    pending: number;
                                    lastNumber: number;
                                }[];
                            };
                        };
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the status of a run */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    experimentName: string;
                    runName: string;
                };
                cookie?: never;
            };
            /** @description Body */
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        runStatus: "completed" | "interrupted" | "canceled";
                    } | {
                        /** @enum {string} */
                        runStatus: "running";
                        resumeFrom?: number;
                    };
                };
            };
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
                /** @description 400 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
                /** @description 403 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/experiments/{experimentName}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    type?: string;
                };
                header?: never;
                path: {
                    experimentName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                            logs: {
                                type: string;
                                number: number;
                                values: {
                                    [key: string]: unknown;
                                };
                            }[];
                        };
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiments/{experimentName}/runs/{runName}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    experimentName: string;
                    runName: string;
                };
                cookie?: never;
            };
            /** @description Body */
            requestBody: {
                content: {
                    "application/json": {
                        logs: {
                            type: string;
                            number: number;
                            values: {
                                [key: string]: unknown;
                            };
                        }[];
                    };
                };
            };
            responses: {
                /** @description 201 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
                /** @description 400 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
                /** @description 403 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
                /** @description 404 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "error";
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
