emit:
  - '@typespec/openapi3'
options:
  '@typespec/openapi3':
    emitter-output-dir: '{output-dir}'
    output-file: 'openapi.yaml'
    file-type: 'yaml'
    seal-object-schemas: true
    openapi-versions:
      - '3.1.0'
linter:
  extends:
    - '@typespec/http/all'

output-dir: '{project-root}'
