# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js 22.x.x
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 22.x.x

      - run: pnpm install

      - run: pnpm run build-all

      - uses: actions/upload-artifact@v4
        with:
          name: 'build'
          path: 'packages/*/dist/'

  test:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js 22.x.x
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 22.x.x

      - run: pnpm install

      - uses: actions/download-artifact@v4
        id: download
        with:
          name: 'build'
          path: 'packages'

      - run: pnpm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install Node.js 22.x.x
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 22.x.x
      - run: pnpm install
      - run: pnpm run lint

  publint:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Install Node.js 22.x.x
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 22.x.x
      - run: pnpm install
      - run: pnpm run build-all
      - uses: actions/download-artifact@v4
        id: download
        with:
          name: 'build'
          path: 'packages'
      - run: pnpm run publint
